spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/websocket?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

jwt:
  access-secret: 1wNcH7ZaDZUxFZF6BNh7paYhgXCxwBTHePd4MPTNZ/c=
  refresh-secret: 3L42/isPL1JnmDeC9fqRowDpXQwqmMZmbg6sXae5u+M=
  access-expiration: 900
  refresh-expiration: 86400
